version: '3.3'

services:
  mysql:
    image: mysql:8.0
    container_name: elfuego_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: el_fuego_db
      MYSQL_USER: elfuego
      MYSQL_PASSWORD: elfuego123
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./server/seed.sql:/docker-entrypoint-initdb.d/seed.sql

volumes:
  mysql_data:
